path:
  # --- shared
  calendar_path: E:\OneDrive\Data\Calendar\cne_calendar.csv
  root_dir: E:\OneDrive\Data\tushare
  daily_data_root_dir: E:\OneDrive\Data\tushare\by_date
  db_struct_path: E:\OneDrive\Data\tushare\db_struct.yaml
  alternative_dir: E:\OneDrive\Data\Alternative
  market_index_path: E:\OneDrive\Data\Market\index.xlsx
  by_instru_pos_dir: E:\OneDrive\Data\tushare\by_instrument\position
  by_instru_pre_dir: E:\OneDrive\Data\tushare\by_instrument\preprocess
  by_instru_min_dir: E:\OneDrive\Data\tushare\by_instrument\minute_bar
  instru_info_path: E:\OneDrive\Data\tushare\instruments.csv

  # --- project
  project_root_dir: E:\Data\Projects\CTA_V6

mkt_idxes:
  equity: 881001.WI
  commodity: NH0100.NHF

universe:
  AU.SHF:
    sectorL0: C
    sectorL1: AUG
  AG.SHF:
    sectorL0: C
    sectorL1: AUG
  CU.SHF:
    sectorL0: C
    sectorL1: MTL
  AL.SHF:
    sectorL0: C
    sectorL1: MTL
  PB.SHF:
    sectorL0: C
    sectorL1: MTL
  ZN.SHF:
    sectorL0: C
    sectorL1: MTL
  NI.SHF:
    sectorL0: C
    sectorL1: MTL
  SN.SHF:
    sectorL0: C
    sectorL1: MTL
  SS.SHF:
    sectorL0: C
    sectorL1: MTL
  AO.SHF:
    sectorL0: C
    sectorL1: MTL
  A.DCE:
    sectorL0: C
    sectorL1: OIL
  B.DCE:
    sectorL0: C
    sectorL1: OIL
  M.DCE:
    sectorL0: C
    sectorL1: OIL
  P.DCE:
    sectorL0: C
    sectorL1: OIL
  Y.DCE:
    sectorL0: C
    sectorL1: OIL
  OI.ZCE:
    sectorL0: C
    sectorL1: OIL
  RM.ZCE:
    sectorL0: C
    sectorL1: OIL
  RU.SHF:
    sectorL0: C
    sectorL1: CHM
  BR.SHF:
    sectorL0: C
    sectorL1: CHM
  BU.SHF:
    sectorL0: C
    sectorL1: CHM
  FU.SHF:
    sectorL0: C
    sectorL1: CHM
  L.DCE:
    sectorL0: C
    sectorL1: CHM
  V.DCE:
    sectorL0: C
    sectorL1: CHM
  EB.DCE:
    sectorL0: C
    sectorL1: CHM
  EG.DCE:
    sectorL0: C
    sectorL1: CHM
  PP.DCE:
    sectorL0: C
    sectorL1: CHM
  PG.DCE:
    sectorL0: C
    sectorL1: CHM
  MA.ZCE:
    sectorL0: C
    sectorL1: CHM
  TA.ZCE:
    sectorL0: C
    sectorL1: CHM
  RB.SHF:
    sectorL0: C
    sectorL1: BLK
  HC.SHF:
    sectorL0: C
    sectorL1: BLK
  I.DCE:
    sectorL0: C
    sectorL1: BLK
  J.DCE:
    sectorL0: C
    sectorL1: BLK
  JM.DCE:
    sectorL0: C
    sectorL1: BLK
  SF.ZCE:
    sectorL0: C
    sectorL1: BLK
  SM.ZCE:
    sectorL0: C
    sectorL1: BLK
  ZC.ZCE:
    sectorL0: C
    sectorL1: BLK
  FG.ZCE:
    sectorL0: C
    sectorL1: BLK
  SA.ZCE:
    sectorL0: C
    sectorL1: BLK
  UR.ZCE:
    sectorL0: C
    sectorL1: BLK
  AP.ZCE:
    sectorL0: C
    sectorL1: AGR
  CF.ZCE:
    sectorL0: C
    sectorL1: AGR
  SR.ZCE:
    sectorL0: C
    sectorL1: AGR
  CY.ZCE:
    sectorL0: C
    sectorL1: AGR
  CJ.ZCE:
    sectorL0: C
    sectorL1: AGR
  PK.ZCE:
    sectorL0: C
    sectorL1: AGR
  JD.DCE:
    sectorL0: C
    sectorL1: AGR
  LH.DCE:
    sectorL0: C
    sectorL1: AGR
  C.DCE:
    sectorL0: C
    sectorL1: AGR
  CS.DCE:
    sectorL0: C
    sectorL1: AGR

available:
  win: 10
  amount_threshold: 100000.00
  win_vol: 60
  win_vol_min: 20

icov:
  win: 60


css:
  vma_win: 5
  vma_threshold: 0.0175
  vma_wgt: 0.2
  sev_win: 20

tst:
  wins: [ 1, 5 ]
  wins_qtest: [ 5 ] # must be subset of wins

# ------- factors -------
factor_decay_default:
  rate: 1.0
  win: 1
factors:
  BASIS:
    args:
      wins: [ 10, 20, 60, 120, 240 ]
  TS:
    args:
      wins: [ 10, 20, 60, 120, 240 ]
  RS:
    args:
      wins: [ 20, 60, 120, 240 ]
  MTM:
    args:
      wins: [ 1, 2, 3, 5, 10, 20, 120, 240 ]
  SKEW:
    args:
      wins: [ 10, 20, 60, 120 ]
  KURT:
    args:
      wins: [ 5, 10, 20, 60, 120, 240 ]
  LIQUIDITY:
    args:
      wins: [ 10, 20, 60, 120, 240 ]
  SIZE:
    args:
      wins: [ 10, 20, 60, 120, 240 ]
  CTP:
    args:
      wins: [ 60, 120, 180 ]
      lbds: [ 0.5, 0.95 ]
  CVP:
    args:
      wins: [ 60, 120, 180 ]
      lbds: [ 0.5, 0.95 ]
  CTR:
    args:
      wins: [ 30, 60, 120 ]
      lbds: [ 0.3, 0.5 ]
  SPDWEB:
    args:
      wins: [ 3, 5, 10, 20 ]
      lbds: [ 0.2, 0.5, 0.8 ]
  MPH:
    args:
      wins: [ 60, 120, 180 ]
      lbds: [ 0.80, 1.00 ]
  S0BETA:
    args:
      wins: [ 20, 60, 120 ]
  S1BETA:
    args:
      wins: [ 20, 60, 120 ]
  VAL:
    args:
      wins: [ 10, 20, 60, 120, 240 ]
  ACR:
    args:
      wins: [ 5, 8, 13, 21, 60, 120 ]
  REOC:
    args:
      wins: [ 3, 5, 10, 20, 60, 120, 240 ]
  NPLS:
    args:
      wins: [ 3, 5, 10, 20, 60, 120, 240 ]
  ONR:
    args:
      wins: [ 3, 5, 10, 20, 60, 120, 240 ]
  ONR2:
    args:
      wins: [ 3, 5, 10, 20, 60, 120, 240 ]
  IDR:
    args:
      wins: [ 3, 5, 10, 20, 60, 120, 240 ]
  VENTROPY:
    args:
      wins: [ 1, 3, 5, 10, 20, 60 ]
  AMP:
    args:
      wins: [ 5, 20, 60, 120, 240 ]
      lbds: [ 0.2, 0.3, 0.5 ]
  LCVR:
    args:
      wins: [ 5, 20, 60, 120, 240 ]
  #  LCRV:
  #    args:
  #      wins: [ 3, 5, 20, 60, 120, 240 ]
  #  SMT:
  #    args:
  #      wins: [ 3, 5 ]
  #      lbds: [ 0.2, 0.5, 0.8 ]
  #  MF:
  #    args:
  #      wins: [ 1, 3, 5, 10 ]
  #  JUMP:
  #    args:
  #      wins: [ 1, 3, 5, 10 ]
  #  IDV:
  #    args:
  #      wins: [ 5, 8, 13, 21, 34, 55 ]
  #  CNVG:
  #    args:
  #      wins: [ 5, 10, 20, 60, 120, 240 ]
  #  WSPLIT:
  #    args:
  #      wins: [ 1, 3, 5 ]
  #      lbds: [ 0.1, 0.2, 0.4 ]
  #  MPC:
  #    args:
  #      wins: [ 60, 120, 180 ]
  #      lbds: [ 0.80, 1.00 ]
  #  ISKEW:
  #    args:
  #      wins: [ 10, 20, 60, 120, 240 ]
  #  IKURT:
  #    args:
  #      wins: [ 10, 20, 60, 120, 240 ]
  #  OMA:
  #    args:
  #      wins: [ 1, 5, 10, 20, 60, 120, 240 ]

# ------- strategies -------
strategies:
  - name: s0
    opt_win: 20
    ret: Opn005L1
    factors:
      - [ BASIS, BASIS060 ]
      - [ RS, RS240PA ]
      - [ VAL, VALDIF ]
      - [ KURT, KURTDIF ]
      - [ LIQUIDITY, LIQUIDITY240 ]
      - [ NPLS, NPLSDIF ]
    #      - [ MTM, MTMDIF ]
    #      - [ SKEW, SKEW060 ]
    #      - [ SIZE, SIZEDIF ]
    #      - [ CTP, CTP060L95 ]
    #      - [ CVP, CVP060L95 ]
    #      - [ MPH, MPH060L80 ]
    #      - [ ACR, ACRDIF ]
    #      - [ REOC, REOCDIF ]
    #      - [ VENTROPY, VENTROPY005 ]
    #      - [ AMP, AMPDIF ]
    #      - [ LCVR, LCVR020 ]
  - name: s1
    opt_win: 20
    ret: Cls005L1
    factors:
      - [ BASIS, BASIS060 ]
      - [ RS, RS240PA ]
      - [ VAL, VALDIF ]
      - [ KURT, KURTDIF ]
      - [ LIQUIDITY, LIQUIDITY240 ]
      - [ NPLS, NPLSDIF ]
    #      - [ MTM, MTMDIF ]
    #      - [ SKEW, SKEW060 ]
    #      - [ SIZE, SIZEDIF ]
    #      - [ CTP, CTP060L95 ]
    #      - [ CVP, CVP060L95 ]
    #      - [ MPH, MPH060L80 ]
    #      - [ ACR, ACRDIF ]
    #      - [ REOC, REOCDIF ]
    #      - [ VENTROPY, VENTROPY005 ]
    #      - [ AMP, AMPDIF ]
    #      - [ LCVR, LCVR020 ]

# ------- models -------
portfolios:
  - name: p0
    strategies_weights:
      s0: 0.5
      s1: 0.5

# ------- const -------
CONST:
  INIT_CASH: 100_000_000
  COST_RATE: 0.0003
  LAG: 1
